#!/bin/sh
set -e

### BEGIN INIT INFO
# Provides:           warpd
# Default-Start:      2 3 4 5
# Default-Stop:       0 1 6
# Description:
#  Loads lightweight, portable, self-sufficient containers for Magento 2 proyect.
### END INIT INFO

### Install 
# 1) sudo cp WARP_PROJECT/.warp/docker/config/etc/init.d/warpd /etc/init.d/
# 2) sudo ln -s /etc/init.d/warpd /etc/rc0.d/K02warpd 
# 3) sudo ln -s /etc/init.d/warpd /etc/rc1.d/K02warpd   
# 4) sudo ln -s /etc/init.d/warpd /etc/rc2.d/S02warpd  
# 5) sudo ln -s /etc/init.d/warpd /etc/rc3.d/S02warpd   
# 6) sudo ln -s /etc/init.d/warpd /etc/rc4.d/S02warpd
# 7) sudo ln -s /etc/init.d/warpd /etc/rc5.d/S02warpd
# 8) sudo ln -s /etc/init.d/warpd /etc/rc6.d/K02warpd

WARP_PROJECT=/data/www/your-project

WARP_FILE="$WARP_PROJECT/warp"

cd $WARP_PROJECT

case "$1" in
	start)

        $WARP_FILE start
		;;

	stop)

		$WARP_FILE stop
		;;

	restart)

		$WARP_FILE stop
		$WARP_FILE start
		;;

	status)
		status
		;;

	*)
		echo "Usage: service warpd {start|stop|restart|status}"
		exit 1
		;;
esac